#!/usr/bin/env bash
# =============================================================================
# Note Assistant — macOS Setup Script
# Auto-detects OS version and chip, installs dependencies, writes config.yaml,
# builds NoteAssistant.app, and places it on the Desktop.
# =============================================================================
set -euo pipefail

# Ensure we don't use an active environment from another project
unset VIRTUAL_ENV
unset PYTHONHOME
unset PYTHONPATH

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[info]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║        Note Assistant — Setup            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# =============================================================================
# 1. Detect macOS version and chip
# =============================================================================
info "Detecting system capabilities..."

OS_VERSION=$(sw_vers -productVersion)
MAJOR=$(echo "$OS_VERSION" | cut -d. -f1)
MINOR=$(echo "$OS_VERSION" | cut -d. -f2)
CHIP=$(uname -m)  # arm64 = Apple Silicon, x86_64 = Intel

info "macOS: $OS_VERSION | Chip: $CHIP"

# Determine best tier
TRANSCRIPTION_BACKEND="faster-whisper"
SUMMARIZATION_BACKEND="ollama"
TIER_NAME="Fallback"

if [ "$MAJOR" -ge 15 ] && [ "$MINOR" -ge 1 ] && [ "$CHIP" = "arm64" ]; then
    TRANSCRIPTION_BACKEND="apple"
    SUMMARIZATION_BACKEND="apple"
    TIER_NAME="Full (Apple Speech + Apple Foundation Models)"
elif [ "$MAJOR" -ge 13 ]; then
    TRANSCRIPTION_BACKEND="apple"
    SUMMARIZATION_BACKEND="ollama"
    TIER_NAME="Partial (Apple Speech + Ollama)"
else
    TRANSCRIPTION_BACKEND="faster-whisper"
    SUMMARIZATION_BACKEND="ollama"
    TIER_NAME="Fallback (faster-whisper + Ollama)"
fi

success "Tier: $TIER_NAME"

# =============================================================================
# 2. Write config.yaml
# =============================================================================
info "Writing config.yaml..."

cat > config.yaml <<EOF
# Note Assistant Configuration
# Auto-generated by setup_mac.sh
# Detected: macOS ${OS_VERSION}, ${CHIP}
# Tier: ${TIER_NAME}

audio:
  source: mic          # mic | system
  sample_rate: 16000
  chunk_seconds: 5

transcription:
  backend: ${TRANSCRIPTION_BACKEND}   # apple | faster-whisper
  language: null
  whisper_model: base  # tiny | base | small | medium | large-v3
  device: auto

summarization:
  backend: ${SUMMARIZATION_BACKEND}   # apple | ollama
  summarize_every: 3
  prompt_template: |
    Summarize the following transcript into concise bullet-point notes:
    {transcript}
  ollama_model: llama3.2
  ollama_host: http://localhost:11434

output:
  save_transcript: true
  save_summary: true
  output_dir: ./notes
  apple_notes: true
  apple_notes_title: "Note Assistant — {date}"
EOF

success "config.yaml written with tier: $TIER_NAME"

# =============================================================================
# 3. Install Homebrew if missing
# =============================================================================
if ! command -v brew &>/dev/null; then
    warn "Homebrew not found. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# =============================================================================
# 4. Install uv
# =============================================================================
if ! command -v uv &>/dev/null; then
    info "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi
success "uv: $(uv --version)"

# =============================================================================
# 5. Create virtual environment and install dependencies
# =============================================================================
info "Creating uv virtual environment (Python 3.12)..."
rm -rf .venv

# Ensure a native Python 3.12 is used.
uv python install 3.12
# Force the exact aarch64 build to avoid miniconda/x86_64 conflicts
uv venv .venv --python cpython-3.12.9-macos-aarch64-none

info "Installing Python dependencies (tier: $TIER_NAME)..."
uv pip install -e "."
uv pip install pillow

# Install extra backends if needed
if [ "$TRANSCRIPTION_BACKEND" = "faster-whisper" ] || [ "$SUMMARIZATION_BACKEND" = "ollama" ]; then
    info "Installing optional backends (faster-whisper/ollama)..."
    # Fallback to older onnxruntime if needed for compatibility
    uv pip install -e ".[extra]"
fi

success "Dependencies installed."

# =============================================================================
# 6. Install BlackHole (system audio capture)
# =============================================================================
if ! system_profiler SPAudioDataType 2>/dev/null | grep -q "BlackHole"; then
    info "Installing BlackHole 2ch (system audio capture)..."
    brew install blackhole-2ch || warn "BlackHole install failed — system audio will not work."
    echo ""
    warn "MANUAL STEP REQUIRED for system audio:"
    warn "  1. Open 'Audio MIDI Setup' (Spotlight → Audio MIDI Setup)"
    warn "  2. Click '+' → 'Create Aggregate Device'"
    warn "  3. Add 'BlackHole 2ch' and your input device"
    warn "  4. Set the Aggregate Device as input in System Settings → Sound"
    echo ""
else
    success "BlackHole already installed."
fi

# =============================================================================
# 7. Check Ollama (if needed)
# =============================================================================
if [ "$SUMMARIZATION_BACKEND" = "ollama" ]; then
    if ! command -v ollama &>/dev/null; then
        warn "Ollama not found. Install from https://ollama.ai and run: ollama pull llama3.2"
    else
        success "Ollama found: $(ollama --version 2>/dev/null || echo 'installed')"
    fi
fi

# =============================================================================
# 8. Build NoteAssistant.app and place on Desktop
# =============================================================================
info "Building NoteAssistant.app..."
bash "$SCRIPT_DIR/build_app.sh"
# =============================================================================
# Done
# =============================================================================
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║           Setup Complete! 🎉             ║"
echo "╚══════════════════════════════════════════╝"
echo ""
success "Tier: $TIER_NAME"
success "NoteAssistant.app placed on Desktop"
echo ""
echo "To start:"
echo "  • Double-click NoteAssistant.app on your Desktop"
echo "  • Or run: uv run python -m note_assistant"
echo "  • Options: uv run python -m note_assistant --help"
echo ""
