#!/usr/bin/env bash
# =============================================================================
# Note Assistant — macOS Setup Script
# Auto-detects OS version and chip, installs dependencies, writes config.yaml,
# builds NoteAssistant.app, and places it on the Desktop.
# =============================================================================
set -euo pipefail

# Ensure we don't use an active environment from another project
unset VIRTUAL_ENV
unset PYTHONHOME
unset PYTHONPATH

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[info]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║        Note Assistant — Setup            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# =============================================================================
# 1. Detect macOS version and chip
# =============================================================================
info "Detecting system capabilities..."

OS_VERSION=$(sw_vers -productVersion)
MAJOR=$(echo "$OS_VERSION" | cut -d. -f1)
CHIP=$(uname -m)  # arm64 = Apple Silicon, x86_64 = Intel

info "macOS: $OS_VERSION | Chip: $CHIP"

# Determine best tier
TRANSCRIPTION_BACKEND="faster-whisper"
SUMMARIZATION_BACKEND="ollama"
TIER_NAME="Fallback"

if [ "$MAJOR" -ge 26 ] && [ "$CHIP" = "arm64" ]; then
    TRANSCRIPTION_BACKEND="apple"
    SUMMARIZATION_BACKEND="apple"
    TIER_NAME="Full (Apple Speech + Apple Foundation Models)"
elif [ "$MAJOR" -ge 13 ]; then
    TRANSCRIPTION_BACKEND="apple"
    SUMMARIZATION_BACKEND="ollama"
    TIER_NAME="Partial (Apple Speech + Ollama)"
else
    TRANSCRIPTION_BACKEND="faster-whisper"
    SUMMARIZATION_BACKEND="ollama"
    TIER_NAME="Fallback (faster-whisper + Ollama)"
fi

success "Tier: $TIER_NAME"

# =============================================================================
# 2. Write config.yaml
# =============================================================================
info "Writing config.yaml..."

cp config.example.yaml config.yaml

# Rewrite header
sed -i '' "1s/.*/# Note Assistant Configuration/" config.yaml
sed -i '' "2s/.*/# Auto-generated by setup_mac.sh/" config.yaml
sed -i '' "2a\\
# Detected: macOS ${OS_VERSION}, ${CHIP}\\
# Tier: ${TIER_NAME}" config.yaml

# Patch backends (section-scoped: range ends at next top-level key)
sed -i '' \
    -e "/^transcription:/,/^[a-z]/s/^\(  backend: \)[a-z-]*/\1${TRANSCRIPTION_BACKEND}/" \
    -e "/^summarization:/,/^[a-z]/s/^\(  backend: \)[a-z-]*/\1${SUMMARIZATION_BACKEND}/" \
    config.yaml

success "config.yaml written with tier: $TIER_NAME"

# =============================================================================
# 3. Install Homebrew if missing
# =============================================================================
if ! command -v brew &>/dev/null; then
    warn "Homebrew not found. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# =============================================================================
# 4. Install uv
# =============================================================================
if ! command -v uv &>/dev/null; then
    info "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi
success "uv: $(uv --version)"

# =============================================================================
# 5. Create virtual environment and install dependencies
# =============================================================================
info "Creating uv virtual environment (Python 3.12)..."
rm -rf .venv

# Ensure a native Python 3.12 is used.
uv python install 3.12
# Force the exact aarch64 build to avoid miniconda/x86_64 conflicts
uv venv .venv --python cpython-3.12.9-macos-aarch64-none

info "Installing Python dependencies (tier: $TIER_NAME)..."
uv pip install -e "." pillow
success "Dependencies installed."

# =============================================================================
# 6. Install BlackHole (system audio capture)
# =============================================================================
if ! system_profiler SPAudioDataType 2>/dev/null | grep -q "BlackHole"; then
    info "Installing BlackHole 2ch (system audio capture)..."
    brew install blackhole-2ch || warn "BlackHole install failed — system audio will not work."
    echo ""
    warn "MANUAL STEP REQUIRED for system audio:"
    warn "  1. Open 'Audio MIDI Setup' (Spotlight → Audio MIDI Setup)"
    warn "  2. Click '+' → 'Create Aggregate Device'"
    warn "  3. Add 'BlackHole 2ch' and your input device"
    warn "  4. Set the Aggregate Device as input in System Settings → Sound"
    echo ""
else
    success "BlackHole already installed."
fi

# =============================================================================
# 7. Check backend dependencies
# =============================================================================
info "Checking backend dependencies..."

if [ "$CHIP" = "arm64" ]; then
    .venv/bin/python -c "import mlx" 2>/dev/null \
        && success "mlx: ok" || warn "mlx not importable — MLX backends will not work"
    .venv/bin/python -c "import mlx_lm" 2>/dev/null \
        && success "mlx-lm: ok" || warn "mlx-lm not importable — MLX summarization will not work"
    .venv/bin/python -c "import mlx_whisper" 2>/dev/null \
        && success "mlx-whisper: ok" || warn "mlx-whisper not importable — MLX transcription will not work"
fi

if [ "$TRANSCRIPTION_BACKEND" = "faster-whisper" ]; then
    .venv/bin/python -c "import faster_whisper" 2>/dev/null \
        && success "faster-whisper: ok" || error "faster-whisper not importable"
fi

if [ "$SUMMARIZATION_BACKEND" = "ollama" ]; then
    if ! command -v ollama &>/dev/null; then
        warn "Ollama CLI not found — install from https://ollama.ai"
    else
        success "Ollama: $(ollama --version 2>/dev/null || echo 'installed')"
    fi
fi

# =============================================================================
# 8. Preload models
# =============================================================================
info "Preloading models..."

WHISPER_MODEL=$(sed -n 's/^  whisper_model: //p' config.yaml)
MLX_WHISPER_MODEL=$(sed -n 's/^  mlx_whisper_model: //p' config.yaml)
MLX_SUMMARIZE_MODEL=$(sed -n 's/^  mlx_model: //p' config.yaml)
OLLAMA_MODEL=$(sed -n 's/^  ollama_model: //p' config.yaml)
OLLAMA_FALLBACK_MODEL=$(sed -n 's/^  ollama_fallback_model: //p' config.yaml)

if [ "$TRANSCRIPTION_BACKEND" = "faster-whisper" ]; then
    info "Downloading faster-whisper model '$WHISPER_MODEL'..."
    .venv/bin/python -c "
from faster_whisper import WhisperModel
WhisperModel('${WHISPER_MODEL}', device='cpu', compute_type='int8')
" && success "faster-whisper '$WHISPER_MODEL' ready."
fi

if [ "$TRANSCRIPTION_BACKEND" = "mlx-whisper" ]; then
    info "Downloading MLX Whisper model '$MLX_WHISPER_MODEL'..."
    .venv/bin/python -c "
from huggingface_hub import snapshot_download
snapshot_download('${MLX_WHISPER_MODEL}')
" && success "MLX Whisper '$MLX_WHISPER_MODEL' ready."
fi

if [ "$SUMMARIZATION_BACKEND" = "mlx" ]; then
    info "Downloading MLX model '$MLX_SUMMARIZE_MODEL' (this may take several minutes)..."
    .venv/bin/python -c "
from mlx_lm import load
load('${MLX_SUMMARIZE_MODEL}')
" && success "MLX model '$MLX_SUMMARIZE_MODEL' ready."
fi

if [ "$SUMMARIZATION_BACKEND" = "ollama" ] && command -v ollama &>/dev/null; then
    for model in "$OLLAMA_MODEL" "$OLLAMA_FALLBACK_MODEL"; do
        if ollama list 2>/dev/null | grep -q "^${model}"; then
            success "Ollama model '$model' already downloaded."
        else
            info "Pulling Ollama model '$model'..."
            ollama pull "$model" && success "Ollama '$model' ready."
        fi
    done
fi

# =============================================================================
# 9. Build NoteAssistant.app and place on Desktop
# =============================================================================
info "Building NoteAssistant.app..."
bash "$SCRIPT_DIR/build_app.sh"
# =============================================================================
# Done
# =============================================================================
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║           Setup Complete! 🎉             ║"
echo "╚══════════════════════════════════════════╝"
echo ""
success "Tier: $TIER_NAME"
success "NoteAssistant.app placed on Desktop"
echo ""
echo "To start:"
echo "  • Double-click NoteAssistant.app on your Desktop"
echo "  • Or run: uv run python -m note_assistant"
echo "  • Options: uv run python -m note_assistant --help"
echo ""
